/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_cond_btn_out;
  button_conditioner_2 cond_btn (
    .clk(clk),
    .in(io_button[4+0-:1]),
    .out(M_cond_btn_out)
  );
  wire [1-1:0] M_pulsebtn1_out;
  edge_detector_3 pulsebtn1 (
    .clk(clk),
    .in(M_cond_btn_out),
    .out(M_pulsebtn1_out)
  );
  wire [1-1:0] M_auto_driver_out;
  blinker_4 auto_driver (
    .clk(clk),
    .rst(~io_dip[0+0+0-:1]),
    .out(M_auto_driver_out)
  );
  wire [1-1:0] M_pulsebtn2_out;
  edge_detector_3 pulsebtn2 (
    .clk(clk),
    .in(M_auto_driver_out),
    .out(M_pulsebtn2_out)
  );
  wire [3-1:0] M_fa_driver_out;
  reg [1-1:0] M_fa_driver_in;
  fsm_4_5 fa_driver (
    .clk(clk),
    .rst(rst),
    .in(M_fa_driver_in),
    .out(M_fa_driver_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    io_led[16+0+3-:4] = M_fa_driver_out;
    M_fa_driver_in = (M_pulsebtn1_out & ~io_dip[0+0+0-:1]) | (M_pulsebtn2_out & io_dip[0+0+0-:1]);
  end
endmodule
