/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module fsm_4_5 (
    input clk,
    input rst,
    input in,
    output reg [2:0] out
  );
  
  
  
  
  localparam OOO_state = 3'd0;
  localparam OOI_state = 3'd1;
  localparam OIO_state = 3'd2;
  localparam OII_state = 3'd3;
  localparam IOO_state = 3'd4;
  localparam IOI_state = 3'd5;
  localparam IIO_state = 3'd6;
  localparam III_state = 3'd7;
  
  reg [2:0] M_state_d, M_state_q = OOO_state;
  
  always @* begin
    M_state_d = M_state_q;
    
    out = 1'h0;
    
    case (M_state_q)
      OOO_state: begin
        out = 1'h0;
        if (in == 1'h1) begin
          M_state_d = OOI_state;
        end
      end
      OOI_state: begin
        out = 1'h1;
        if (in == 1'h1) begin
          M_state_d = OIO_state;
        end
      end
      OIO_state: begin
        out = 4'ha;
        if (in == 1'h1) begin
          M_state_d = OII_state;
        end
      end
      OII_state: begin
        out = 4'hb;
        if (in == 1'h1) begin
          M_state_d = IOO_state;
        end
      end
      IOO_state: begin
        out = 7'h64;
        if (in == 1'h1) begin
          M_state_d = IOI_state;
        end
      end
      IOI_state: begin
        out = 7'h65;
        if (in == 1'h1) begin
          M_state_d = IIO_state;
        end
      end
      IIO_state: begin
        out = 7'h6e;
        if (in == 1'h1) begin
          M_state_d = III_state;
        end
      end
      III_state: begin
        out = 7'h6f;
        if (in == 1'h1) begin
          M_state_d = OOO_state;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
